name: Changesets PR or Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc

      - run: yarn install

      - name: Set git user
        run: |
          git config --global user.email "surim014@naver.com"
          git config --global user.name "Sonny"

      - name: Create Changesets Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          title: "chore: version packages"
          commit: |
            chore: version packages

            Co-authored-by: Surim Son <surim014@naver.com>
            Co-authored-by: Jooyoung Cho <jzo09@naver.com>
            Co-authored-by: Hyojeong Shin <shinyojeong@naver.com>
          version: yarn changeset:version
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
